services:
    db:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_DB: walrus

    walrus-dev:
        build:
            context: .
        ports:
            - "3000:3000"
        environment:
            - RUST_ENV=development
        env_file:
            - .env
            - .env.local
        volumes:
            - ./env:/app/.env:ro
        develop:
            watch:
                - path: ./src
                  action: rebuild
                - path: ./public
                  action: rebuild
                - path: ./Cargo.toml
                  action: rebuild
        profiles:
            - dev
        depends_on:
            - db

    walrus:
        build:
            context: .
        ports:
            - "8000:8000"
        restart: unless-stopped
        environment:
            - RUST_ENV=production
        profiles:
            - prod
